version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 14.x

    commands:
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/bin/composer
      - npm install -g yarn
      - npm i aws-sdk
      - yum install -y jq
  pre_build:
    commands:
     - composer update
      - composer install
      - yarn install
      - echo export AWS_DEFAULT_REGION=$CSC_AWS_DEFAULT_REGION >> environment.txt
  
  build:
    commands:
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan view:clear
  
  post_build:
    commands:
      - yarn run prod

  artifacts:
  files:
    - '**/*'   
