version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 12.x

    commands:
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/bin/composer
      - npm install -g yarn
      - npm i aws-sdk
      - yum install -y jq

     build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install
     - cp extra/.env ./
     - php artisan cache:clear

 post_build:
   commands:
     - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
  
